#!/bin/sh

if [ -z "$@" ]; then
	set -e

	{ \
		echo "[www]"; \
		echo "pm = ${FPM_PM:-static}"
		echo "pm.max_children = ${FPM_MAX_CHILDREN:-2}"; \
		echo "pm.start_servers = ${FPM_START_SERVERS:-2}"; \
		echo "pm.min_spare_servers = ${FPM_MIN_SPARE_SERVERS:-2}"; \
		echo "pm.max_spare_servers = ${FPM_MAX_SPARE_SERVERS:-10}"; \
		echo "pm.max_requests = ${FPM_MAX_REQUESTS:-100}"; \
	} | tee /usr/local/etc/php-fpm.d/zzz-docker.conf

	{ \
		echo '[php]'; \
		echo "memory_limit = ${PHP_MEMORY_LIMIT:-512M}"; \
		echo "post_max_size = ${PHP_POST_MAX_SIZE:-256M}"; \
		echo "upload_max_filesize = ${PHP_UPLOAD_MAX_SIZE:-128M}"; \
	} | tee /usr/local/etc/php/php.ini

	if [ -e /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ]; then
		if [ -z ${XDEBUG_REMOTE_HOST} ]; then
			{ \
				echo "[Xdebug]"; \
				echo "xdebug.remote_enable = 1"; \
				echo "xdebug.remote_connect_back = 1"; \
				echo "xdebug.remote_port = ${XDEBUG_REMOTE_PORT:-9000}"; \
				echo "xdebug.profiler_enable_trigger = 1"; \
				echo "xdebug.profiler_output_dir=/data/log"; \
			} | tee /usr/local/etc/php/conf.d/xdebug.ini
		else
			{ \
				echo "[Xdebug]"; \
				echo "xdebug.remote_enable = 1"; \
				echo "xdebug.remote_host = ${XDEBUG_REMOTE_HOST}"; \
				echo "xdebug.remote_port = ${XDEBUG_REMOTE_PORT:-9000}"; \
				echo "xdebug.profiler_enable_trigger = 1"; \
				echo "xdebug.profiler_output_dir=/data/log"; \
			} | tee /usr/local/etc/php/conf.d/xdebug.ini
		fi
	fi
fi

# now run original entrypoint

exec docker-php-entrypoint "$@"
