version: 2.1

commands:
  build_and_push_docker_image:
    parameters:
      tag:
        type: string
      subdir:
        type: string
    steps:
      - run:
          name: Build image
          command: MAJOR_TAG=`echo "<< parameters.tag >>" | sed -nre 's/^[^0-9]*(([0-9]+\.)?[0-9]+).*/\1/p'` && docker build -t senasi/php:<< parameters.tag >> -t senasi/php:${MAJOR_TAG} << parameters.subdir >>
      - run:
          name: Push image
          command: docker push senasi/php:<< parameters.tag >>
      - run:
          name: Push base image
          command: MAJOR_TAG=`echo "<< parameters.tag >>" | sed -nre 's/^[^0-9]*(([0-9]+\.)?[0-9]+).*/\1/p'` && docker push senasi/php:${MAJOR_TAG}

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Docker hub login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - build_and_push_docker_image:
          tag: ${CIRCLE_TAG}
          subdir: base
      - build_and_push_docker_image:
          tag: ${CIRCLE_TAG}-devel
          subdir: devel
      - build_and_push_docker_image:
          tag: ${CIRCLE_TAG}-nginx
          subdir: nginx

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
