version: 2.1

commands:
  build_and_push_docker_image:
    parameters:
      sufix:
        type: string
      subdir:
        type: string
    steps:
      - run:
          name: Build image
          command: MAJOR_TAG=`echo "${CIRCLE_TAG}" | sed -nre 's/^[^0-9]*(([0-9]+\.)?[0-9]+).*/\1/p'` && docker build -t senasi/php:${CIRCLE_TAG}<< parameters.sufix >> -t senasi/php:${MAJOR_TAG}<< parameters.sufix >> << parameters.subdir >>
      - run:
          name: Push image
          command: docker push senasi/php:${CIRCLE_TAG}<< parameters.sufix >>
      - run:
          name: Push major tag image
          command: MAJOR_TAG=`echo "${CIRCLE_TAG}" | sed -nre 's/^[^0-9]*(([0-9]+\.)?[0-9]+).*/\1/p'` && docker push senasi/php:${MAJOR_TAG}<< parameters.sufix >>

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Docker hub login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - build_and_push_docker_image:
          sufix: ""
          subdir: base
      - build_and_push_docker_image:
          sufix: "-devel"
          subdir: devel
      - build_and_push_docker_image:
          sufix: "-nginx"
          subdir: nginx

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
