version: 2.1

commands:
  build_and_push_docker_image:
    parameters:
      basetag:
        type: string
      tag:
        type: string
      subdir:
        type: string
    steps:
      - run:
          name: Build image
          command: docker build -t senasi/php:<< parameters.tag >> -t senasi/php:<< parameters.basetag >> << parameters.subdir >>
      - run:
          name: Push image
          command: docker push senasi/php:<< parameters.tag >>
       - run:
          name: Push base image
          command: docker push senasi/php:<< parameters.basetag >>

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Docker hub login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - build_and_push_docker_image:
          basetag: ${CIRCLE_BRANCH}
          tag: ${CIRCLE_TAG}
          subdir: base
      - build_and_push_docker_image:
          basetag: ${CIRCLE_BRANCH}-devel
          tag: ${CIRCLE_TAG}-devel
          subdir: devel
      - build_and_push_docker_image:
          basetag: ${CIRCLE_BRANCH}-nginx
          tag: ${CIRCLE_TAG}-nginx
          subdir: nginx

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
