#!/bin/sh

set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
  set -- php-fpm "$@"
fi

# exec or source scripts in /docker-php-entrypoint.d/
# script needs to have .sh extension
# files with +x will be executed in new shell

for file in /docker-php-entrypoint.d/*.sh; do
  # POSIX friendly nullglob checking && directory checking
  if [ ! -f "${file}" ]; then
    continue
  fi

  if [ -x "${file}" ]; then
    echo "Executing ${file}"
    "${file}"
  else
    echo "Sourcing ${file}"
    # shellcheck source=docker-php-entrypoint.d/
    . "${file}"
  fi
done

exec "$@"
