#!/bin/sh

# running composer
if [ "$1" = "composer" ]; then
  CURRENT_UID=$(id -u)
  PWD_USER=$(stat -c '%u' "$PWD")

  if [ "$CURRENT_UID" = "0" ] && [ "$PWD_USER" != "0" ]; then
    PWD_GROUP=$(stat -c '%g' "$PWD")

    GROUP_EXISTS=$(getent group "$PWD_GROUP" || echo -1)
    USER_EXISTS=$(getent passwd "$PWD_USER" || echo -1)

    NAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)

  if [ "$GROUP_EXISTS" = "-1" ]; then
      addgroup -g "$PWD_GROUP" -S "$NAME"
  fi

  if [ "$USER_EXISTS" = "-1" ]; then
      GROUP_NAME=$(getent group "$PWD_GROUP" | cut -d: -f1)
      adduser -S -D -u "$PWD_USER" -s /sbin/nologin -G "$NAME" -g "$GROUP_NAME" "$NAME"
  fi

    USER_NAME=$(getent passwd "$PWD_USER" | cut -d: -f1)

    exec su-exec "$USER_NAME" "$@"
  fi
fi

# running php-fpm
if [ "$1" = "php-fpm" ] || [ "${1#-}" != "$1" ]; then
	set -e

	{ \
		echo "[www]"; \
		echo "pm = ${FPM_PM:-static}"
		echo "pm.max_children = ${FPM_MAX_CHILDREN:-2}"; \
		echo "pm.start_servers = ${FPM_START_SERVERS:-2}"; \
		echo "pm.min_spare_servers = ${FPM_MIN_SPARE_SERVERS:-2}"; \
		echo "pm.max_spare_servers = ${FPM_MAX_SPARE_SERVERS:-10}"; \
		echo "pm.max_requests = ${FPM_MAX_REQUESTS:-100}"; \
	} | tee /usr/local/etc/php-fpm.d/zzz-docker.conf

	{ \
		echo "[php]"; \
		echo "expose_php = off"; \
		echo "memory_limit = ${PHP_MEMORY_LIMIT:-512M}"; \
		echo "post_max_size = ${PHP_POST_MAX_SIZE:-256M}"; \
		echo "upload_max_filesize = ${PHP_UPLOAD_MAX_SIZE:-128M}"; \
	} | tee /usr/local/etc/php/php.ini

	if [ -e /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ]; then
    { \
      echo "[Xdebug]"; \
      echo "xdebug.mode=develop,debug,profile,trace,gcstats"; \
      echo "xdebug.start_with_request=trigger"; \
      if [ -z "${XDEBUG_CLIENT_HOST}" ]; then \
        echo "xdebug.discover_client_host=true"; \
      else \
        echo "xdebug.client_host=${XDEBUG_CLIENT_HOST}"; \
      fi; \
      echo "xdebug.client_port = ${XDEBUG_CLIENT_PORT:-9003}"; \
      echo "xdebug.output_dir=/data/log"; \
      echo "xdebug.idekey = \"${XDEBUG_IDE_KEY:-PHPSTORM}\""; \
    } | tee /usr/local/etc/php/conf.d/xdebug.ini
	fi
fi

# now run original entrypoint
exec docker-php-entrypoint "$@"
