#!/bin/sh

# wrapper for composer to run it as owner of current working directory

current_uid=$(id -u)
pwd_uid=$(stat -c '%u' "$PWD")

if [ "${current_uid}" = "0" ] && [ "${pwd_uid}" != "0" ]; then
  pwd_uid_gid=$(stat -c '%u:%g' "$PWD")
  export COMPOSER_HOME="/tmp/.composer-${pwd_uid}"
  exec su-exec "${pwd_uid_gid}" /usr/local/bin/composer-real "$@"
fi

exec /usr/local/bin/composer-real "$@"
