on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string
      suffix:
        required: false
        type: string
        default: ''
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            senasi/php
          flavor: |
            latest=false
            suffix=${{ inputs.suffix }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push
        id: build_push
        uses: docker/build-push-action@v5
        with:
          context: {{defaultContext}}:${{ inputs.folder }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
