name: Build and push docker images

on:
  push:
    tags:
      - "*"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build base image
        uses: ./.github/workflows/build-one.yml
        with:
          context: './base'
      - name: Build devel image
        uses: ./.github/workflows/build-one.yml
        with:
          context: './devel'
          suffix: '-devel'
      - name: Build nginx image
        uses: ./.github/workflows/build-one.yml
        with:
          context: './nginx'
          suffix: '-nginx'
