name: Build and push docker images

on:
  push:
    tags:
      - "*"

jobs:
  build_base:
    uses: ./.github/workflows/build-one.yml
    with:
      context: './base'
  build_devel:
    needs: build_base
    uses: ./.github/workflows/build-one.yml
    with:
      context: './devel'
      suffix: '-devel'
  build_nginx:
    needs: build_base
    uses: ./.github/workflows/build-one.yml
    with:
      context: './nginx'
      suffix: '-nginx'
